defaults:
    - override hydra/launcher: submitit_local

task: tdmpc2-plan
sub_task: origin-scratch-test # scratch # sub_task = exp_name
exp_name: origin-scratch-test

# environment
multitask: false
setpoint: 70
reward_type: classic
action_type: continuous
observation_type: classic

# evaluation
checkpoint: null
eval_episodes: 1
eval_freq: 1_000
eval_enable: true

# training
steps: 50_000
batch_size: 1024
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 2.0
rho: 0.5
lr: 3e-4
weight_decay: 1e-6
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 10_000
eval_buffer_size: 1_000
data_dir: null # /inspire/hdd/ws-f4d69b29-e0a5-44e6-bd92-acf4de9990f0/public-project/chenxinyan-240108120066/chenxinyan/industrialbenchmark-master/industrial_benchmark_python/data/data_demo.pkl
eval_data_dir: null # /inspire/hdd/ws-f4d69b29-e0a5-44e6-bd92-acf4de9990f0/public-project/chenxinyan-240108120066/chenxinyan/industrialbenchmark-master/industrial_benchmark_python/data/data_demo_eval.pkl
pretrained_path: null # /inspire/hdd/ws-f4d69b29-e0a5-44e6-bd92-acf4de9990f0/public-project/chenxinyan-240108120066/chenxinyan/tdmpc2/logs/tdmpc2-transition/origin_re/models/29000.pt

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
obs: state
model_size: 5
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
state_dim: 6
latent_dim: 512
task_dim: 0
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_entity: moss_chen
wandb_silent: false
disable_wandb: false
save_csv: false
offline_wandb: true

# misc
save_video: false
save_agent: true
save_dynamics: false
dynamic_save_path: null
seed: 212

# convenience
work_dir: ???
task_title: ???
obs_shape: ???
action_dim: 3
episode_length: 101
obs_shapes: ???
action_dims: ???
episode_lengths: 101
seed_steps: ???
bin_size: ???
